# Generated by Django 4.2.10 on 2025-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(verbose_name='単語')),
                ('meaning', models.TextField(verbose_name='意味')),
                ('yomikatakana', models.CharField(verbose_name='読みカタカナ')),
                ('pronunciation', models.CharField(verbose_name='発音')),
                ('part_of_speech', models.CharField(verbose_name='品詞')),
                ('sentence_eng', models.TextField(verbose_name='例文')),
                ('sentence_jpn', models.TextField(verbose_name='例文訳')),
                ('category', models.CharField(verbose_name='カテゴリー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'Vocabulary',
            },
        ),
    ]
