# Generated by Django 4.2.10 on 2025-07-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='category',
            field=models.CharField(blank=True, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.CharField(blank=True, verbose_name='品詞'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='pronunciation',
            field=models.CharField(blank=True, verbose_name='発音'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='sentence_eng',
            field=models.TextField(blank=True, verbose_name='例文'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='sentence_jpn',
            field=models.TextField(blank=True, verbose_name='例文訳'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='yomikatakana',
            field=models.CharField(blank=True, verbose_name='読みカタカナ'),
        ),
    ]
