# Generated by Django 4.2.10 on 2025-07-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_vocabulary_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ('id',), 'verbose_name_plural': 'Vocabulary'},
        ),
    ]
